### ISSUE TITLE
Stretch Setup Script: ImportError: cannot import name '_imagingtk' in zynthian.service

### ISSUE THREAD

**Issue by guysoft** [zynthian/zynthian-sys#28]
Hey,
So I am trying to start ``zynthian.service``, but I see it fails with this error:
```
Feb 06 22:43:55 jackpi startx[20337]: Traceback (most recent call last):
Feb 06 22:43:55 jackpi startx[20337]:   File "/usr/local/lib/python3.5/dist-packages/PIL/ImageTk.py", line 176, in paste
Feb 06 22:43:55 jackpi startx[20337]:     tk.call("PyImagingPhoto", self.__photo, block.id)
Feb 06 22:43:55 jackpi startx[20337]: _tkinter.TclError: invalid command name "PyImagingPhoto"
Feb 06 22:43:55 jackpi startx[20337]: During handling of the above exception, another exception occurred:
Feb 06 22:43:55 jackpi startx[20337]: Traceback (most recent call last):
Feb 06 22:43:55 jackpi startx[20337]:   File "./zynthian_gui.py", line 39, in <module>
Feb 06 22:43:55 jackpi startx[20337]:     import zynautoconnect
Feb 06 22:43:55 jackpi startx[20337]:   File "/home/pi/zynthian-ui/zynautoconnect/__init__.py", line 5, in <module>
Feb 06 22:43:55 jackpi startx[20337]:     from zynautoconnect.zynthian_autoconnect import *
Feb 06 22:43:55 jackpi startx[20337]:   File "/home/pi/zynthian-ui/zynautoconnect/zynthian_autoconnect.py", line 34, in <module>
Feb 06 22:43:55 jackpi startx[20337]:     from zyngui import zynthian_gui_config
Feb 06 22:43:55 jackpi startx[20337]:   File "/home/pi/zynthian-ui/zyngui/__init__.py", line 22, in <module>
Feb 06 22:43:55 jackpi startx[20337]:     import zyngui.zynthian_gui_config as zynthian_gui_config
Feb 06 22:43:55 jackpi startx[20337]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_config.py", line 332, in <module>
Feb 06 22:43:55 jackpi startx[20337]:     loading_imgs.append(ImageTk.PhotoImage(pil_frame2))
Feb 06 22:43:55 jackpi startx[20337]:   File "/usr/local/lib/python3.5/dist-packages/PIL/ImageTk.py", line 115, in __init__
Feb 06 22:43:55 jackpi startx[20337]:     self.paste(image)
Feb 06 22:43:55 jackpi startx[20337]:   File "/usr/local/lib/python3.5/dist-packages/PIL/ImageTk.py", line 180, in paste
Feb 06 22:43:55 jackpi startx[20337]:     from PIL import _imagingtk
Feb 06 22:43:55 jackpi startx[20337]: ImportError: cannot import name '_imagingtk'
```
What version of PIL is needed?

**Comment by guysoft** [comment]
The following solved the issue:

```
sudo pip3 install -I --no-cache-dir Pillow
sudo apt-get remove python-pip python3-pip
cd /tmp
wget https://bootstrap.pypa.io/get-pip.py
sudo python get-pip.py ; sudo python3 get-pip.py
sudo pip3 install requests
```

**Comment by jofemodo** [comment]
This package should be installed during mod-ui building process. If it's not installed, then something was wrong with the mod-ui recipe. I'm trying to build an image for test the fixes and see if the problems is solved.

**Comment by guysoft** [comment]
Ok found why,
This is the console output in the installation. pip explodes:
```
+ ./setup_mod.sh
Cloning into 'mod-host'...
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/mod-monitor.o src/monitor/monitor-client.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/socket.o src/socket.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/uridmap.o src/uridmap.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/mod-host.o src/mod-host.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/protocol.o src/protocol.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/effects.o src/effects.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/utils.o src/utils.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/completer.o src/completer.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/lv2_evbuf.o src/lv2_evbuf.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/monitor.o src/monitor.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/symap.o src/symap.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/worker.o src/worker.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/sha1/sha1.o src/sha1/sha1.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a7 -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/rtmempool/rtmempool.o src/rtmempool/rtmempool.c
cc src/mod-monitor.o -Wl,--no-undefined -s -L/usr/local/lib -ljack -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lreadline -lpthread -lrt -lm -lfftw3 -lfftw3f -lfftw3_threads -lfftw3f_threads -shared -o mod-monitor.so
cc ./src/socket.o ./src/uridmap.o ./src/mod-host.o ./src/protocol.o ./src/effects.o ./src/utils.o ./src/completer.o ./src/lv2_evbuf.o ./src/monitor.o ./src/symap.o ./src/worker.o ./src/sha1/sha1.o ./src/rtmempool/rtmempool.o -Wl,--no-undefined -s -L/usr/local/lib -ljack -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lreadline -lpthread -lrt -lm -lfftw3 -lfftw3f -lfftw3_threads -lfftw3f_threads -o mod-host
cc ./src/socket.o ./src/uridmap.o ./src/mod-host.o ./src/protocol.o ./src/effects.o ./src/utils.o ./src/completer.o ./src/lv2_evbuf.o ./src/monitor.o ./src/symap.o ./src/worker.o ./src/sha1/sha1.o ./src/rtmempool/rtmempool.o -Wl,--no-undefined -s -L/usr/local/lib -ljack -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lreadline -lpthread -lrt -lm -lfftw3 -lfftw3f -lfftw3_threads -lfftw3f_threads -shared -o mod-host.so
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
sudo: unable to resolve host stretch
install -d /usr/local/share/man/man1/
install -m 644 doc/*.1 /usr/local/share/man/man1/
install -d /usr/local/bin
install -m 755 mod-host /usr/local/bin
install -d /usr/lib/arm-linux-gnueabihf/jack/
install -m 755 mod-host.so /usr/lib/arm-linux-gnueabihf/jack/
install -m 755 mod-monitor.so /usr/lib/arm-linux-gnueabihf/jack/
Cloning into 'mod-ui'...
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
sudo: unable to resolve host stretch
Collecting Pillow==2.8.1 (from -r requirements.txt (line 1))
  Downloading https://www.piwheels.hostedpi.com/simple/pillow/Pillow-2.8.1-cp35-cp35m-linux_armv7l.whl (904kB)
Collecting pyserial==2.7 (from -r requirements.txt (line 2))
  Downloading https://www.piwheels.hostedpi.com/simple/pyserial/pyserial-2.7-py3-none-any.whl (75kB)
Collecting pystache==0.5.4 (from -r requirements.txt (line 3))
  Downloading https://www.piwheels.hostedpi.com/simple/pystache/pystache-0.5.4-py3-none-any.whl (89kB)
Collecting tornado==4.1 (from -r requirements.txt (line 4))
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 837, in _validate_conn
    conn.connect()
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 281, in connect
    conn = self._new_conn()
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xf23f55d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
```

**Comment by guysoft** [comment]
I did a quick and dirty fix on my end for now: https://github.com/guysoft/ZynthianOS/commit/71fa1329dbc05286f0c83cbd1d1e776a4ff728b2

**Comment by jofemodo** [comment]
OK! By now, the Q&D fix is OK. When the process runs without problems, i will see what should be moved from the "start_chroot_script" to the zynthian setup script.
