### ISSUE TITLE
Mod-host fails because of pycrypto

### ISSUE THREAD

**Issue by guysoft** [zynthian/zynthian-sys#53]
See

```
+ cd /zynthian/zynthian-sys/scripts
+ ./setup_mod.sh
Cloning into 'mod-host'...
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/mod-monitor.o src/monitor/monitor-client.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/socket.o src/socket.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/uridmap.o src/uridmap.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/mod-host.o src/mod-host.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/protocol.o src/protocol.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/effects.o src/effects.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/lv2_evbuf.o src/lv2_evbuf.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/completer.o src/completer.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/monitor.o src/monitor.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/worker.o src/worker.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/symap.o src/symap.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/utils.o src/utils.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/sha1/sha1.o src/sha1/sha1.c
cc -I/usr/local/include/lilv-0 -I/usr/local/include/sratom-0 -I/usr/local/include -I/usr/local/include/sord-0 -I/usr/local/include/serd-0  -DHAVE_FFTW335 -DHAVE_NEW_LILV -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -mneon-for-64bits -mfloat-abi=hard -mvectorize-with-neon-quad -O3 -Wall -Wextra -c -std=gnu99 -fPIC -D_GNU_SOURCE -fvisibility=hidden -o src/rtmempool/rtmempool.o src/rtmempool/rtmempool.c
cc src/mod-monitor.o -Wl,--no-undefined -s -L/usr/local/lib -ljack -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lreadline -lpthread -lrt -lm -lfftw3 -lfftw3f -lfftw3_threads -lfftw3f_threads -shared -o mod-monitor.so
cc ./src/socket.o ./src/uridmap.o ./src/mod-host.o ./src/protocol.o ./src/effects.o ./src/lv2_evbuf.o ./src/completer.o ./src/monitor.o ./src/worker.o ./src/symap.o ./src/utils.o ./src/sha1/sha1.o ./src/rtmempool/rtmempool.o -Wl,--no-undefined -s -L/usr/local/lib -ljack -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lreadline -lpthread -lrt -lm -lfftw3 -lfftw3f -lfftw3_threads -lfftw3f_threads -o mod-host
cc ./src/socket.o ./src/uridmap.o ./src/mod-host.o ./src/protocol.o ./src/effects.o ./src/lv2_evbuf.o ./src/completer.o ./src/monitor.o ./src/worker.o ./src/symap.o ./src/utils.o ./src/sha1/sha1.o ./src/rtmempool/rtmempool.o -Wl,--no-undefined -s -L/usr/local/lib -ljack -llilv-0 -ldl -lsratom-0 -lsord-0 -lserd-0 -lreadline -lpthread -lrt -lm -lfftw3 -lfftw3f -lfftw3_threads -lfftw3f_threads -shared -o mod-host.so
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
sudo: unable to resolve host zynthianOS
install -d /usr/local/share/man/man1/
install -m 644 doc/*.1 /usr/local/share/man/man1/
install -d /usr/local/bin
install -m 755 mod-host /usr/local/bin
install -d /usr/lib/arm-linux-gnueabihf/jack/
install -m 755 mod-host.so /usr/lib/arm-linux-gnueabihf/jack/
install -m 755 mod-monitor.so /usr/lib/arm-linux-gnueabihf/jack/
Cloning into 'mod-ui'...
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
Unknown host QEMU_IFLA type: 40
Unknown host QEMU_IFLA type: 41
sudo: unable to resolve host zynthianOS
Collecting Pillow==2.8.1 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/85/3a/6308c0bfe01410e38d576e6656843398aaa81d953660e8010e0a4727d553/Pillow-2.8.1.tar.gz (9.0MB)
Collecting pyserial==2.7 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/df/c9/d9da7fafaf2a2b323d20eee050503ab08237c16b0119c7bbf1597d53f793/pyserial-2.7.tar.gz (122kB)
Collecting pystache==0.5.4 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/d6/fd/eb8c212053addd941cc90baac307c00ac246ac3fce7166b86434c6eae963/pystache-0.5.4.tar.gz (75kB)
Requirement already satisfied: tornado==4.1 in /usr/local/lib/python3.5/dist-packages (from -r requirements.txt (line 4)) (4.1)
Collecting pycrypto-2.7a1 from http://github.com/dlitz/pycrypto/tarball/v2.7a1#egg=pycrypto-2.7a1 (from -r requirements.txt (line 5))
  Downloading http://github.com/dlitz/pycrypto/tarball/v2.7a1
  Running setup.py (path:/tmp/pip-install-dg2e4ykr/pycrypto-2.7a1/setup.py) egg_info for package pycrypto-2.7a1 produced metadata for project name pycrypto. Fix your #egg=pycrypto-2.7a1 fragments.
Requirement already satisfied: certifi in /usr/local/lib/python3.5/dist-packages (from tornado==4.1->-r requirements.txt (line 4)) (2018.4.16)
Building wheels for collected packages: Pillow, pyserial, pystache, pycrypto, pycrypto
  Running setup.py bdist_wheel for Pillow: started
  Running setup.py bdist_wheel for Pillow: still running...
  Running setup.py bdist_wheel for Pillow: still running...
  Running setup.py bdist_wheel for Pillow: still running...
  Running setup.py bdist_wheel for Pillow: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/cd/ea/20/30882ee1340d97a7c64d98157fa0b552f5126b569b18641fe8
  Running setup.py bdist_wheel for pyserial: started
  Running setup.py bdist_wheel for pyserial: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a9/c2/0c/6c73a54255ad3a05a7fa6567e34f1d2c283d929492f8e297bf
  Running setup.py bdist_wheel for pystache: started
  Running setup.py bdist_wheel for pystache: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a6/e9/b0/a29a4f37e8f5a765473dd7936ef025d9d2543e07b55d88697c
  Running setup.py bdist_wheel for pycrypto: started
  Running setup.py bdist_wheel for pycrypto: still running...
  Running setup.py bdist_wheel for pycrypto: still running...
  Running setup.py bdist_wheel for pycrypto: finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-pge7y05w/wheels/2f/3a/c0/f43592eb88ed348bcdb223bf6d145e418769b8be2952d72910
  Running setup.py bdist_wheel for pycrypto: started
  Running setup.py bdist_wheel for pycrypto: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dg2e4ykr/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-nlhm0vvf --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-dg2e4ykr/pycrypto/setup.py'
  
  ----------------------------------------
  Failed building wheel for pycrypto
  Running setup.py clean for pycrypto
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dg2e4ykr/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/lib/python3.5/tokenize.py", line 454, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-dg2e4ykr/pycrypto/setup.py
```

**Comment by guysoft** [comment]
Fixed, install pycrypto before everything solves it
