### ISSUE TITLE
Problems with installing touchosc2midi

### ISSUE THREAD

**Issue by dcoredump** [zynthian/zynthian-sys#9]
Hi,

installing from a fresh **zynthian_gorgona_rbpi3-2016-12-21.img** throws an error at the first call of /zynthian/zynthian-sys/scripts/update_zynthian.sh:

```
# sh install_touchosc2midi.sh 
Cloning into 'touchosc2midi'...
remote: Counting objects: 141, done.
remote: Total 141 (delta 0), reused 0 (delta 0), pack-reused 141
Receiving objects: 100% (141/141), 24.09 KiB | 0 bytes/s, done.
Resolving deltas: 100% (63/63), done.
Checking connectivity... done.
Unpacking /zynthian/zynthian-sw/touchosc2midi
  Running setup.py (path:/tmp/pip-Bg8PUK-build/setup.py) egg_info for package from file:///zynthian/zynthian-sw/touchosc2midi
    
Downloading/unpacking mido==1.1.24 (from touchosc2midi==0.0.10)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 194, in find_requirement
    page = self._get_page(main_index_url, req)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_page
    session=self.session,
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 694, in get_page
    req, link, "connection error: %s" % exc, url,
TypeError: __str__ returned non-string (type Error)

Storing debug log for failure in /root/.pip/pip.log
```

**Comment by jofemodo** [comment]
Several packages must be upgraded. A full system upgrade solves the problem.
